version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/loader

jobs:
  publish:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Make Gradlew Executable
          command: chmod +x gradlew
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Assemble Release
          command: ./gradlew lib:assembleRelease
      - run:
          name: Publish Artifact
          command: ./gradlew lib:bintrayUpload

workflows:
  version: 2.1
  build:
    jobs:
      - approve_publish:
          type: approval
          filters:
            branches:
              only: master
      - publish:
          requires:
            - approve_publish
          filters:
            branches:
              only: master
